/**
 * Detects banned phrases and ensures numeric consistency in AI responses.
 * @param {string} responseText - The text generated by the LLM
 * @param {Object} truthObject - The deterministic truth object
 * @returns {boolean} - True if safe, False if unsafe
 */
export const validateResponse = (responseText, truthObject) => {
    if (!responseText) return false;
    const lowerText = responseText.toLowerCase();

    // 1. Banned Phrases (Anti-Institutional)
    const bannedPhrases = [
        "bunk", "skip class", "evade", "cheat", "ignore compliance", 
        "don't worry about attendance", "optimize for 75"
    ];

    for (const phrase of bannedPhrases) {
        if (lowerText.includes(phrase)) {
            console.warn(`Guardrail Triggered: Banned phrase found: "${phrase}"`);
            return false;
        }
    }

    // 2. Numeric Consistency Check (Basic) - Ensure AI doesn't hallucinate wild numbers
    // This is hard to do perfectly with regex on natural language, but we can check if it mentions 
    // a percentage vastly different from the truth.
    // For V1 Hybrid, we rely mostly on the system prompt instruction to use the provided data.
    // A strict check would involve extracting all % numbers and matching them against truth details.
    
    // Simple check: If truth says < 75%, AI should not say "You are safe" (unless referencing a specific safe course)
    if (truthObject.status === "CRITICAL" && lowerText.includes("you are safe") && !lowerText.includes("except")) {
         console.warn("Guardrail Triggered: Context Mismatch (Critical Status vs 'Safe' message)");
         return false;
    }

    return true;
};

/**
 * Fallback response generator when LLM fails or hits guardrails.
 * @param {Object} truthObject 
 * @returns {string} Safe template response
 */
export const getSafeFallback = (truthObject) => {
    const { attendancePercent, details } = truthObject;
    
    if (truthObject.status === "NO_ENROLLMENT") {
        return "You are not enrolled in any courses yet.";
    }

    const report = details.map(d => `${d.courseName}: ${d.percentage}%`).join('\n');
    return `Here is your accurate attendance report based on official records:\n\n${report}\n\nOverall: ${attendancePercent}%. Target: ${truthObject.institutionalTarget}%.`;
};
